### ISSUE TITLE
Can't detect my character's position

### ISSUE THREAD

**Issue by JuanPasos** [ephell/Sadidauto-Dofus-Retro-Bot#68]
Hey there! By any chance, would you know why am I getting this error?

2024-03-28 19:12:52.671 | INFO | 'Tactical Mode' option is already on.
2024-03-28 19:12:52.806 | INFO | 'Models' toggle icon is visible.
2024-03-28 19:12:52.836 | INFO | Turning on 'Models' option ...
2024-03-28 19:12:53.252 | INFO | Successfully turned on 'Models' option.
2024-03-28 19:12:53.252 | INFO | Detecting character position by model circles ...
2024-03-28 19:12:53.723 | ERROR | RecoverableException: Failed to detect character position by circles.

2024-03-28 19:12:55.549 | CRITICAL | Traceback (most recent call last):
  File "C:\Users\jp\Desktop\Sadidauto-Dofus-Retro-Bot\src\bot\bot.py", line 102, in run
    self._in_combat_controller.run()
  File "C:\Users\jp\Desktop\Sadidauto-Dofus-Retro-Bot\src\bot\_states\in_combat\controller.py", line 38, in run
    self._fighter.fight()
  File "C:\Users\jp\Desktop\Sadidauto-Dofus-Retro-Bot\src\bot\_states\in_combat\_sub_states\fighting\fighter.py", line 34, in fight
    raise e
  File "C:\Users\jp\Desktop\Sadidauto-Dofus-Retro-Bot\src\bot\_states\in_combat\_sub_states\fighting\fighter.py", line 28, in fight
    FirstTurnHandler.handle(self._script, self._character_name)
  File "C:\Users\jp\Desktop\Sadidauto-Dofus-Retro-Bot\src\bot\_states\in_combat\_sub_states\fighting\_first_turn_handler\handler.py", line 25, in handle
    cls._handle_models_toggle_icon_visible(script, character_name)
  File "C:\Users\jp\Desktop\Sadidauto-Dofus-Retro-Bot\src\bot\_states\in_combat\_sub_states\fighting\_first_turn_handler\handler.py", line 35, in _handle_models_toggle_icon_visible
    character_pos = CharacterFinder.find_by_circles(character_name)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jp\Desktop\Sadidauto-Dofus-Retro-Bot\src\bot\_states\in_combat\_sub_states\fighting\_character_finder.py", line 55, in find_by_circles
    raise RecoverableException("Failed to detect character position by circles.")
src.bot._exceptions.RecoverableException: Failed to detect character position by circles.

I already double-checked my setup and everything seems alright. I'd really appreciate if you could help me.

Pic is showing last sec before I get disconnected
![wh](https://github.com/ephell/Sadidauto-Dofus-Retro-Bot/assets/122598521/89b906a2-a2f9-4951-bcf8-fbaa3a052b3e)

**Comment by ephell** [comment]
Fixed in: #69.
