### ISSUE TITLE
Failing after "Health bar is not visible"

### ISSUE THREAD

**Issue by sadidmonster** [ephell/Sadidauto-Dofus-Retro-Bot#70]
![image](https://github.com/ephell/Sadidauto-Dofus-Retro-Bot/assets/165616325/2715ac7e-e37a-4001-9171-18d77d9274a7)

```
2024-04-01 07:28:25.554 | INFO | Verifying character's name ...
2024-04-01 07:28:25.556 | INFO | Opening 'Characteristics' interface ...
2024-04-01 07:28:25.860 | INFO | Successfully opened 'Characteristics' interface!
2024-04-01 07:28:26.137 | INFO | Successfully verified character's name!
2024-04-01 07:28:26.137 | INFO | Closing 'Characteristics' interface ...
2024-04-01 07:28:26.443 | INFO | Successfully closed 'Characteristics' interface!
2024-04-01 07:28:26.556 | INFO | Reading character's level ...
2024-04-01 07:28:26.556 | INFO | Opening 'Characteristics' interface ...
2024-04-01 07:28:26.861 | INFO | Successfully opened 'Characteristics' interface!
2024-04-01 07:28:27.139 | INFO | Successfully read character's level: 36!
2024-04-01 07:28:27.140 | INFO | Closing 'Characteristics' interface ...
2024-04-01 07:28:27.443 | INFO | Successfully closed 'Characteristics' interface!
2024-04-01 07:28:27.544 | INFO | 'DisturbanceChecker' thread has started.
2024-04-01 07:28:27.783 | INFO | Determined bot state: State.OUT_OF_COMBAT.
2024-04-01 07:28:27.783 | INFO | Getting inventory pods percentage ...
2024-04-01 07:28:27.784 | INFO | Opening 'Inventory' interface ...
2024-04-01 07:28:28.312 | INFO | Successfully opened 'Inventory' interface!
2024-04-01 07:28:28.413 | INFO | Getting occupied pods percentage ...
2024-04-01 07:28:28.933 | INFO | Inventory is 44.62% full.
2024-04-01 07:28:28.933 | INFO | Closing 'Inventory' interface ...
2024-04-01 07:28:29.344 | INFO | Successfully closed 'Inventory' interface!
2024-04-01 07:28:29.711 | ERROR | RecoverableException: Health bar is not visible.
2024-04-01 07:28:29.711 | INFO | Screenshotting the game window ...
2024-04-01 07:28:29.821 | INFO | Saving the screenshot for debug ...
2024-04-01 07:28:29.849 | INFO | Screenshot saved!
2024-04-01 07:28:29.849 | INFO | Exception 'ExceptionReason.UNSPECIFIED' occurred '1' times in a row.
2024-04-01 07:28:29.849 | INFO | Attempting to recover ...
2024-04-01 07:28:29.878 | INFO | Closing all interfaces ...
2024-04-01 07:28:29.995 | INFO | 'DisturbanceChecker' thread is paused because recovery is in progress.
2024-04-01 07:28:31.263 | INFO | Finished closing all interfaces.
2024-04-01 07:28:31.263 | INFO | Successfully recovered!
2024-04-01 07:28:31.468 | INFO | Determined bot state: State.OUT_OF_COMBAT.
2024-04-01 07:28:31.468 | INFO | 'DisturbanceChecker' thread has resumed.
2024-04-01 07:28:31.710 | ERROR | RecoverableException: Health bar is not visible.
2024-04-01 07:28:31.710 | INFO | Screenshotting the game window ...
2024-04-01 07:28:31.814 | INFO | Saving the screenshot for debug ...
2024-04-01 07:28:31.841 | INFO | Screenshot saved!
2024-04-01 07:28:31.841 | INFO | Exception 'ExceptionReason.UNSPECIFIED' occurred '2' times in a row.
2024-04-01 07:28:31.842 | INFO | Attempting to recover ...
2024-04-01 07:28:31.860 | INFO | Closing all interfaces ...
2024-04-01 07:28:31.943 | INFO | 'DisturbanceChecker' thread is paused because recovery is in progress.
2024-04-01 07:28:33.160 | INFO | Finished closing all interfaces.
2024-04-01 07:28:33.160 | INFO | Successfully recovered!
2024-04-01 07:28:33.352 | INFO | Determined bot state: State.OUT_OF_COMBAT.
2024-04-01 07:28:33.352 | INFO | 'DisturbanceChecker' thread has resumed.
2024-04-01 07:28:33.594 | ERROR | RecoverableException: Health bar is not visible.
2024-04-01 07:28:33.594 | INFO | Screenshotting the game window ...
2024-04-01 07:28:33.700 | INFO | Saving the screenshot for debug ...
2024-04-01 07:28:33.728 | INFO | Screenshot saved!
2024-04-01 07:28:33.728 | INFO | Exception 'ExceptionReason.UNSPECIFIED' occurred '3' times in a row.
2024-04-01 07:28:33.729 | INFO | Attempting to recover ...
2024-04-01 07:28:33.760 | INFO | Closing all interfaces ...
2024-04-01 07:28:33.810 | INFO | 'DisturbanceChecker' thread is paused because recovery is in progress.
2024-04-01 07:28:35.076 | INFO | Finished closing all interfaces.
2024-04-01 07:28:35.077 | INFO | Successfully recovered!
2024-04-01 07:28:35.268 | INFO | Determined bot state: State.OUT_OF_COMBAT.
2024-04-01 07:28:35.268 | INFO | 'DisturbanceChecker' thread has resumed.
2024-04-01 07:28:35.510 | ERROR | RecoverableException: Health bar is not visible.
2024-04-01 07:28:35.511 | INFO | Screenshotting the game window ...
2024-04-01 07:28:35.625 | INFO | Saving the screenshot for debug ...
2024-04-01 07:28:35.658 | INFO | Screenshot saved!
2024-04-01 07:28:35.659 | CRITICAL | UnrecoverableExpection: Same exception 'ExceptionReason.UNSPECIFIED' occurred '3' times in a row within '120' seconds.
2024-04-01 07:28:35.659 | INFO | Screenshotting the game window ...
2024-04-01 07:28:35.749 | INFO | Saving the screenshot for debug ...
2024-04-01 07:28:35.761 | INFO | 'DisturbanceChecker' thread is paused because recovery is in progress.
2024-04-01 07:28:35.776 | INFO | Screenshot saved!
2024-04-01 07:28:35.778 | CRITICAL | Traceback (most recent call last):
File "C:\Projects\Sadidauto-Dofus-Retro-Bot-main\src\bot\bot.py", line 99, in run
self._out_of_combat_controller.run()
File "C:\Projects\Sadidauto-Dofus-Retro-Bot-main\src\bot\_states\out_of_combat\controller.py", line 28, in run
result = self._hunter.hunt()
^^^^^^^^^^^^^^^^^^^
File "C:\Projects\Sadidauto-Dofus-Retro-Bot-main\src\bot\_states\out_of_combat\_sub_states\hunting\hunter.py", line 76, in hunt
if not HpRecoverer.is_health_bar_full():
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Projects\Sadidauto-Dofus-Retro-Bot-main\src\bot\_states\out_of_combat\_sub_states\hunting\_hp_recoverer\hp_recoverer.py", line 50, in is_health_bar_full
raise RecoverableException("Health bar is not visible.")
src.bot._exceptions.RecoverableException: Health bar is not visible.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "C:\Projects\Sadidauto-Dofus-Retro-Bot-main\src\bot\bot.py", line 105, in run
self._recoverer.recover(e.reason, e.occured_in_sub_state)
File "C:\Projects\Sadidauto-Dofus-Retro-Bot-main\src\bot\_recoverer\recoverer.py", line 62, in recover
self._check_exception_consecutiveness(exception_reason)
File "C:\Projects\Sadidauto-Dofus-Retro-Bot-main\src\bot\_recoverer\recoverer.py", line 95, in _check_exception_consecutiveness
raise UnrecoverableException(
src.bot._exceptions.UnrecoverableException: Same exception 'ExceptionReason.UNSPECIFIED' occurred '3' times in a row within '120' seconds.

2024-04-01 07:28:35.778 | INFO | Attempting to logout ...
2024-04-01 07:28:36.006 | INFO | Opening 'Main Menu' interface ...
2024-04-01 07:28:36.183 | INFO | Clicking 'X' button ...
2024-04-01 07:28:36.845 | INFO | Successfully clicked 'X' button!
2024-04-01 07:28:37.112 | INFO | Successfully opened 'Main Menu' interface!
2024-04-01 07:28:37.113 | INFO | Clicking 'Logout' button ...
2024-04-01 07:28:37.648 | INFO | Successfully clicked 'Logout' button!
2024-04-01 07:28:37.919 | INFO | Clicking 'Yes' button ...
2024-04-01 07:28:38.489 | INFO | Successfully clicked 'Yes' button!
2024-04-01 07:28:38.827 | INFO | Successfully logged out!
2024-04-01 07:28:38.828 | INFO | Exiting ...
```

(I've removed character name in screenshot and trace)

Also, I don't yet have poisoned wind; is that a breaking reason?

**Comment by ephell** [comment]
Hello, thank you for raising the issue, @sadidmonster .

1) To answer your question: no, not having **Poisoned Wind** in the spell bar shouldn't cause a crash, especially not while outside of combat. 
2) By looking at your screenshot, I can see that you have map coordinates enabled in the top left corner.  This one of the many settings that are configured in the [Dofus Configuration Guide](https://github.com/ephell/Sadidauto-Dofus-Retro-Bot/wiki/2.-Dofus-Configuration-Guide). Please make sure your Dofus settings are an exact match. Perhaps you also missed one of the other settings and it somehow impacts the issue you're having.
3) Due to issue #68 I have recently added another step in the [first use guide](https://github.com/ephell/Sadidauto-Dofus-Retro-Bot/wiki/4.-First-Use) that you may have accidentally missed, which is related to setting the Windows display scale to 100%.
4) What **Flash Quality** setting do you have set in **Options Menu -> Display -> Flash Quality**?

**Comment by ephell** [comment]
Closing

**Comment by ephell** [comment]
Closing this as no update was received from the issue raiser.

**Comment by sadidmonster** [comment]
Yes, I've confirmed the map coords are off and all other settings are done exactly as in wiki, still getting stuck here:

I also use f.lux and ScreenDimmer software - but made sure those were off as well.

```
2024-04-09 14:53:52.598 | INFO | Preparing Dofus window ...
2024-04-09 14:53:52.630 | INFO | Successfully prepared 'Mycharname - Dofus Retro v1.42.4' Dofus window!
2024-04-09 14:53:52.630 | INFO | Verifying character's name ...
2024-04-09 14:53:52.631 | INFO | Opening 'Characteristics' interface ...
2024-04-09 14:53:52.939 | INFO | Successfully opened 'Characteristics' interface!
2024-04-09 14:53:53.323 | INFO | Successfully verified character's name!
2024-04-09 14:53:53.329 | INFO | Closing 'Characteristics' interface ...
2024-04-09 14:53:53.638 | INFO | Successfully closed 'Characteristics' interface!
2024-04-09 14:53:53.758 | INFO | Reading character's level ...
2024-04-09 14:53:53.758 | INFO | Opening 'Characteristics' interface ...
2024-04-09 14:53:54.072 | INFO | Successfully opened 'Characteristics' interface!
2024-04-09 14:53:54.349 | INFO | Successfully read character's level: 48!
2024-04-09 14:53:54.349 | INFO | Closing 'Characteristics' interface ...
2024-04-09 14:53:54.672 | INFO | Successfully closed 'Characteristics' interface!
2024-04-09 14:53:54.773 | INFO | 'DisturbanceChecker' thread has started.
2024-04-09 14:53:55.013 | INFO | Determined bot state: State.OUT_OF_COMBAT.
2024-04-09 14:53:55.014 | INFO | Getting inventory pods percentage ...
2024-04-09 14:53:55.014 | INFO | Opening 'Inventory' interface ...
2024-04-09 14:53:55.523 | INFO | Successfully opened 'Inventory' interface!
2024-04-09 14:53:55.625 | INFO | Getting occupied pods percentage ...
2024-04-09 14:53:56.161 | INFO | Inventory is 61.57% full.
2024-04-09 14:53:56.162 | INFO | Closing 'Inventory' interface ...
2024-04-09 14:53:56.572 | INFO | Successfully closed 'Inventory' interface!
2024-04-09 14:53:56.938 | ERROR | RecoverableException: Health bar is not visible.
2024-04-09 14:53:56.938 | INFO | Screenshotting the game window ...
2024-04-09 14:53:57.051 | INFO | Saving the screenshot for debug ...
2024-04-09 14:53:57.082 | INFO | Screenshot saved!
2024-04-09 14:53:57.082 | INFO | Exception 'ExceptionReason.UNSPECIFIED' occurred '1' times in a row.
2024-04-09 14:53:57.082 | INFO | Attempting to recover ...
2024-04-09 14:53:57.107 | INFO | Closing all interfaces ...
2024-04-09 14:53:57.222 | INFO | 'DisturbanceChecker' thread is paused because recovery is in progress.
2024-04-09 14:53:58.524 | INFO | Finished closing all interfaces.
2024-04-09 14:53:58.524 | INFO | Successfully recovered!
2024-04-09 14:53:58.721 | INFO | Determined bot state: State.OUT_OF_COMBAT.
2024-04-09 14:53:58.722 | INFO | 'DisturbanceChecker' thread has resumed.
2024-04-09 14:53:58.972 | ERROR | RecoverableException: Health bar is not visible.
2024-04-09 14:53:58.972 | INFO | Screenshotting the game window ...
2024-04-09 14:53:59.084 | INFO | Saving the screenshot for debug ...
2024-04-09 14:53:59.108 | INFO | Screenshot saved!
2024-04-09 14:53:59.108 | INFO | Exception 'ExceptionReason.UNSPECIFIED' occurred '2' times in a row.
2024-04-09 14:53:59.108 | INFO | Attempting to recover ...
2024-04-09 14:53:59.138 | INFO | Closing all interfaces ...
2024-04-09 14:53:59.188 | INFO | 'DisturbanceChecker' thread is paused because recovery is in progress.
2024-04-09 14:54:00.522 | INFO | Finished closing all interfaces.
2024-04-09 14:54:00.522 | INFO | Successfully recovered!
2024-04-09 14:54:00.722 | INFO | Determined bot state: State.OUT_OF_COMBAT.
2024-04-09 14:54:00.723 | INFO | 'DisturbanceChecker' thread has resumed.
2024-04-09 14:54:00.968 | ERROR | RecoverableException: Health bar is not visible.
2024-04-09 14:54:00.968 | INFO | Screenshotting the game window ...
2024-04-09 14:54:01.081 | INFO | Saving the screenshot for debug ...
2024-04-09 14:54:01.110 | INFO | Screenshot saved!
2024-04-09 14:54:01.110 | INFO | Exception 'ExceptionReason.UNSPECIFIED' occurred '3' times in a row.
2024-04-09 14:54:01.110 | INFO | Attempting to recover ...
2024-04-09 14:54:01.141 | INFO | Closing all interfaces ...
2024-04-09 14:54:01.188 | INFO | 'DisturbanceChecker' thread is paused because recovery is in progress.
2024-04-09 14:54:02.523 | INFO | Finished closing all interfaces.
2024-04-09 14:54:02.523 | INFO | Successfully recovered!
2024-04-09 14:54:02.721 | INFO | Determined bot state: State.OUT_OF_COMBAT.
2024-04-09 14:54:02.722 | INFO | 'DisturbanceChecker' thread has resumed.
2024-04-09 14:54:02.973 | ERROR | RecoverableException: Health bar is not visible.
2024-04-09 14:54:02.973 | INFO | Screenshotting the game window ...
2024-04-09 14:54:03.082 | INFO | Saving the screenshot for debug ...
2024-04-09 14:54:03.109 | INFO | Screenshot saved!
2024-04-09 14:54:03.109 | CRITICAL | UnrecoverableExpection: Same exception 'ExceptionReason.UNSPECIFIED' occurred '3' times in a row within '120' seconds.
2024-04-09 14:54:03.109 | INFO | Screenshotting the game window ...
2024-04-09 14:54:03.223 | INFO | 'DisturbanceChecker' thread is paused because recovery is in progress.
2024-04-09 14:54:03.224 | INFO | Saving the screenshot for debug ...
2024-04-09 14:54:03.251 | INFO | Screenshot saved!
2024-04-09 14:54:03.253 | CRITICAL | Traceback (most recent call last):
File "C:\Projects\Sadidauto-Dofus-Retro-Bot-main\src\bot\bot.py", line 99, in run
self._out_of_combat_controller.run()
File "C:\Projects\Sadidauto-Dofus-Retro-Bot-main\src\bot\_states\out_of_combat\controller.py", line 28, in run
result = self._hunter.hunt()
^^^^^^^^^^^^^^^^^^^
File "C:\Projects\Sadidauto-Dofus-Retro-Bot-main\src\bot\_states\out_of_combat\_sub_states\hunting\hunter.py", line 76, in hunt
if not HpRecoverer.is_health_bar_full():
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Projects\Sadidauto-Dofus-Retro-Bot-main\src\bot\_states\out_of_combat\_sub_states\hunting\_hp_recoverer\hp_recoverer.py", line 50, in is_health_bar_full
raise RecoverableException("Health bar is not visible.")
src.bot._exceptions.RecoverableException: Health bar is not visible.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "C:\Projects\Sadidauto-Dofus-Retro-Bot-main\src\bot\bot.py", line 105, in run
self._recoverer.recover(e.reason, e.occured_in_sub_state)
File "C:\Projects\Sadidauto-Dofus-Retro-Bot-main\src\bot\_recoverer\recoverer.py", line 62, in recover
self._check_exception_consecutiveness(exception_reason)
File "C:\Projects\Sadidauto-Dofus-Retro-Bot-main\src\bot\_recoverer\recoverer.py", line 95, in _check_exception_consecutiveness
raise UnrecoverableException(
src.bot._exceptions.UnrecoverableException: Same exception 'ExceptionReason.UNSPECIFIED' occurred '3' times in a row within '120' seconds.

2024-04-09 14:54:03.254 | INFO | Attempting to logout ...
2024-04-09 14:54:03.508 | INFO | Opening 'Main Menu' interface ...
2024-04-09 14:54:03.710 | INFO | Clicking 'X' button ...
2024-04-09 14:54:04.408 | INFO | Successfully clicked 'X' button!
2024-04-09 14:54:04.711 | INFO | Successfully opened 'Main Menu' interface!
2024-04-09 14:54:04.711 | INFO | Clicking 'Logout' button ...
2024-04-09 14:54:05.291 | INFO | Successfully clicked 'Logout' button!
2024-04-09 14:54:05.585 | INFO | Clicking 'Yes' button ...
2024-04-09 14:54:06.177 | INFO | Successfully clicked 'Yes' button!
2024-04-09 14:54:06.544 | INFO | Successfully logged out!
2024-04-09 14:54:06.544 | INFO | Exiting ...
```

Any idea what's happening?

![image](https://github.com/ephell/Sadidauto-Dofus-Retro-Bot/assets/165616325/05ebe7bb-a334-40e5-ae0a-7de4355eceeb)

**Comment by ephell** [comment]
I cannot reproduce this issue. Must be something on your system then that's impacting this if, as you say, all the settings are correct. I might need to just rewrite the health bar detection logic. I suggest you join the Sadidauto [Discord](https://discord.gg/nqHAXGYxbc) server and I will let you know as soon as I fix this so you can test it out.
